Fix compilation error for 'unit-strip_schema_from_query-t.cpp'
Test failed to compile due to missing type definition:

```
In file included from /usr/include/c++/15.2.1/memory:80,
                 from unit_test.h:13,
                 from unit-strip_schema_from_query-t.cpp:3:
/usr/include/c++/15.2.1/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = SQLite3_result]’:
/usr/include/c++/15.2.1/bits/unique_ptr.h:398:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = SQLite3_result; _Dp = std::default_delete<SQLite3_result>]’
  398 |           get_deleter()(std::move(__ptr));
      |           ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~
/home/javjarfer/Projects/proxysql/include/MySQL_LDAP_Authentication.hpp:24:68:   required from here
   24 |         virtual std::unique_ptr<SQLite3_result> dump_all_users() { return 0; };
      |                                                                           ^
/usr/include/c++/15.2.1/bits/unique_ptr.h:90:23: error: invalid application of ‘sizeof’ to incomplete type ‘SQLite3_result’
   90 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
```